hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("waypaper --restore")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("mako")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("hyprctl setcursor Adwaita 24")

	-- GNOME Keyring (system secrets)
	hl.exec_cmd("gnome-keyring-daemon --start --components=secrets,pkcs11,ssh")
end)
